import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import ConsoleWelcome from "@/components/ConsoleWelcome";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CHMSU - ALUMNI REGISTRY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConsoleWelcome /> {/* Add this line */}
        {children}
        {/* Mounted once at the root: every toast() call in the dashboard was
            rendering nothing, because the only <Toaster> lived inside
            /test-feedback. Imported from "sonner" directly rather than from
            components/ui/sonner, which pulls in the uninstalled next-themes. */}
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
